[package]
name = "discro"
description = "Discrete Observables for asynchronous Functional Reactive Programming (FRP)"
version = "0.0.5"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/discro"
keywords = ["async", "await", "reactive", "observable", "synchronization"]
categories = ["asynchronous", "concurrency"]
edition = "2021"

[patch.crates-io]
# TODO: Remove after v1.19.0 has been released
tokio = { git = "https://github.com/uklotzde/tokio", branch = "tokio-v1.18.x-send_if_modified" }

[dependencies]
async-trait = "0.1.53"
thiserror = "1.0.31"
tokio = { version = "1.18.2", optional = true, default-features = false, features = [
    "sync",
] }

[features]
default = []
tokio = ["dep:tokio"]
# Temporary workaround until tokio v0.19.0 is released
tokio-send_if_modified = ["tokio"]

# Customize the docs.rs build
# https://docs.rs/about/metadata
[package.metadata.docs.rs]
features = ["tokio"]
rustdoc-args = ["--cfg", "docs_rs"]
